version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "internal"
      - "dependencies"
    # Disable version updates, only make PRs for security updates
    open-pull-requests-limit: 0
